#pragma once

#include <cpuid.h>
#include <stdint.h>

/* CPUID Features */
#define CPU_FEATURE_SSE3       (1llu << 0) 
#define CPU_FEATURE_PCLMUL     (1llu << 1)
#define CPU_FEATURE_DTES64     (1llu << 2)
#define CPU_FEATURE_MONITOR    (1llu << 3)  
#define CPU_FEATURE_DS_CPL     (1llu << 4)  
#define CPU_FEATURE_VMX        (1llu << 5)  
#define CPU_FEATURE_SMX        (1llu << 6)  
#define CPU_FEATURE_EST        (1llu << 7)  
#define CPU_FEATURE_TM2        (1llu << 8)  
#define CPU_FEATURE_SSSE3      (1llu << 9)  
#define CPU_FEATURE_CID        (1llu << 10)
#define CPU_FEATURE_SDBG       (1llu << 11)
#define CPU_FEATURE_FMA        (1llu << 12)
#define CPU_FEATURE_CX16       (1llu << 13) 
#define CPU_FEATURE_XTPR       (1llu << 14) 
#define CPU_FEATURE_PDCM       (1llu << 15) 
#define CPU_FEATURE_PCID       (1llu << 17) 
#define CPU_FEATURE_DCA        (1llu << 18) 
#define CPU_FEATURE_SSE4_1     (1llu << 19) 
#define CPU_FEATURE_SSE4_2     (1llu << 20) 
#define CPU_FEATURE_X2APIC     (1llu << 21) 
#define CPU_FEATURE_MOVBE      (1llu << 22) 
#define CPU_FEATURE_POPCNT     (1llu << 23) 
#define CPU_FEATURE_ECX_TSC    (1llu << 24) 
#define CPU_FEATURE_AES        (1llu << 25) 
#define CPU_FEATURE_XSAVE      (1llu << 26) 
#define CPU_FEATURE_OSXSAVE    (1llu << 27) 
#define CPU_FEATURE_AVX        (1llu << 28)
#define CPU_FEATURE_F16C       (1llu << 29)
#define CPU_FEATURE_RDRAND     (1llu << 30)
#define CPU_FEATURE_HYPERVISOR (1llu << 31)
#define CPU_FEATURE_FPU        (1llu << 32)  
#define CPU_FEATURE_VME        (1llu << 33)  
#define CPU_FEATURE_DE         (1llu << 34)  
#define CPU_FEATURE_PSE        (1llu << 35)  
#define CPU_FEATURE_EDX_TSC    (1llu << 36)  
#define CPU_FEATURE_MSR        (1llu << 37)  
#define CPU_FEATURE_PAE        (1llu << 38)  
#define CPU_FEATURE_MCE        (1llu << 39)  
#define CPU_FEATURE_CX8        (1llu << 40)  
#define CPU_FEATURE_APIC       (1llu << 41)  
#define CPU_FEATURE_SEP        (1llu << 42) 
#define CPU_FEATURE_MTRR       (1llu << 43) 
#define CPU_FEATURE_PGE        (1llu << 44) 
#define CPU_FEATURE_MCA        (1llu << 45) 
#define CPU_FEATURE_CMOV       (1llu << 46) 
#define CPU_FEATURE_PAT        (1llu << 47) 
#define CPU_FEATURE_PSE36      (1llu << 48) 
#define CPU_FEATURE_PSN        (1llu << 49) 
#define CPU_FEATURE_CLFLUSH    (1llu << 50) 
#define CPU_FEATURE_DS         (1llu << 51) 
#define CPU_FEATURE_ACPI       (1llu << 52) 
#define CPU_FEATURE_MMX        (1llu << 53) 
#define CPU_FEATURE_FXSR       (1llu << 54) 
#define CPU_FEATURE_SSE        (1llu << 55) 
#define CPU_FEATURE_SSE2       (1llu << 56) 
#define CPU_FEATURE_SS         (1llu << 57) 
#define CPU_FEATURE_HTT        (1llu << 58) 
#define CPU_FEATURE_TM         (1llu << 59) 
#define CPU_FEATURE_IA64       (1llu << 60)
#define CPU_FEATURE_PBE        (1llu << 61)

extern uint64_t cpu_features;

#define cpu_has_feature(FEATURE) (cpu_features & FEATURE)
#define get_cpu_feature_value(feature) (cpu_has_feature(feature) ? 1 : 0)